<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE buzon_de_entrada [
<!ELEMENT buzon_de_entrada (correo)>
<!ELEMENT correo (remitente, destinatario, asunto, cuerpo)>
<!ELEMENT remitente (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>
]>
<buzon_de_entrada>
    <correo>
        <remitente>correo1@gmail.com</remitente>
        <destinatario>correo2@gmail.com</destinatario>
        <asunto>Documentos XML</asunto>
        <cuerpo>Ejercicio 2 sobre los ficheros XML, lenguaje de marcas.</cuerpo>
    </correo>
</buzon_de_entrada>