=== iker0411/Lenguajedemarca2324/xml/Ejercicio_presentacion_XSD/Ejercicio1_Iker_Mendez.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
      

  <xs:element name="pedido">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cliente" type="ClienteType"/>
        <xs:element name="producto" type="ProductoType"/>
        <xs:element name="direccion" type="DireccionType"/>
        <xs:element name="fecha_entrega" type="xs:date"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="ClienteType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ProductoType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DireccionType">
    <xs:sequence>
      <xs:element name="calle" type="xs:string"/>
      <xs:element name="numero" type="xs:integer"/>
      <xs:element name="piso" type="xs:string"/>
      <xs:element name="letra" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== iker0411/Lenguajedemarca2324/xml/Ejercicio_presentacion_XSD/Ejercicio1_Iker_Mendez.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Ejercicio1_Iker_Mendez.xsd">
  <cliente>
    <nombre>Juan Delgado Mart√≠nez</nombre>
  </cliente>
  <producto>
    <nombre>Bicicleta A2023</nombre>
  </producto>
  <direccion>
    <calle>Barco</calle>
    <numero>4</numero>
    <piso>3</piso>
    <letra>A</letra>
  </direccion>
  <fecha_entrega>2000-05-19</fecha_entrega>
</pedido>
