=== iker0411/Lenguajedemarca2324/xml/Ejercicio_presentacion_XSD/Ejercicio6_Iker_Mendez.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://example.com/temporada"
           targetNamespace="http://example.com/temporada"
           elementFormDefault="qualified">

  <xs:element name="temporada">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="año">
          <xs:complexType>
            <xs:attribute name="año" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="piloto">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="apellido" type="xs:string"/>
              <xs:element name="acrónimo">
                <xs:complexType>
                  <xs:attribute name="acro" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="país" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="escudería">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="país" type="xs:string"/>
              <xs:element name="pilotos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="piloto">
                      <xs:complexType>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="circuitos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="circuito">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="país" type="xs:string"/>
                    <xs:element name="podium">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="piloto">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="nombre" type="xs:string"/>
                                <xs:element name="posición" type="xs:integer"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== iker0411/Lenguajedemarca2324/xml/Ejercicio_presentacion_XSD/Ejercicio6_Iker_Mendez.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<temporada xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="Ejercicio6_Iker_Mendez.xsd">
    <año año="2024"/>
    <piloto>
        <nombre>Juan</nombre>
        <apellido>Palma</apellido>
        <acrónimo acro="JUP"/>
        <país>España</país>
    </piloto>
    <escudería>
        <nombre>Ferrari</nombre>
        <país>Italia</país>
        <pilotos>
            <piloto>
                <nombre>Juan</nombre>
            </piloto>
        </pilotos>
    </escudería>
    <circuitos>
        <circuito>
            <nombre>Circuito de Mónaco</nombre>
            <país>Italia</país>
            <podium>
                <piloto>
                    <nombre>Juan</nombre>
                    <posición>1</posición>
                </piloto>
                <piloto>
                    <nombre>Manuel</nombre>
                    <posición>2</posición>
                </piloto>
                <piloto>
                    <nombre>Iker</nombre>
                    <posición>3</posición>
                </piloto>
            </podium>
        </circuito>
    </circuitos>
</temporada>
