=== iker0411/Lenguajedemarca2324/xml/Ejercicio_presentacion_XSD/Ejercicio5_Iker_Mendez.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="clientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cliente" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="dni" type="xs:string"/>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="cuentas">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="cuenta" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="numero" type="xs:long"/>
                          <xs:element name="saldo" type="xs:decimal"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="prestamos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="prestamo" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="id" type="xs:integer"/>
                          <xs:element name="principal" type="xs:string"/>
                          <xs:element name="plazo_en_meses" type="xs:integer"/>
                          <xs:element name="fecha_comienzo" type="xs:date"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== iker0411/Lenguajedemarca2324/xml/Ejercicio_presentacion_XSD/Ejercicio5_Iker_Mendez.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="Ejercicio5_Iker_Mendez.xsd">
    <cliente>
        <dni>2443432s</dni>
        <nombre>Juan</nombre>
        <cuentas>
            <cuenta>
                <numero>2898547545478</numero>
                <saldo>2958</saldo>
            </cuenta>
        </cuentas>
        <prestamos>
            <prestamo>
                <id>3</id>
                <principal>Casa</principal>
                <plazo_en_meses>10</plazo_en_meses>
                <fecha_comienzo>2023-03-26</fecha_comienzo>
            </prestamo>
        </prestamos>
    </cliente>
</clientes>
